{
    "name": "Manage Accountant Report",
    "version": "14.0.1.0.0",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "LGPL-3",
    "installable": True,
    "depends": [
        "mail",
        "ssi_accountant",
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/sequence_template_accountant_report_data.xml",
        "data/policy_template_accountant_report_data.xml",
        "data/approval_template_accountant_report_data.xml",
        "views/accountant_report_opinion_views.xml",
        "views/accountant_report_method_views.xml",
        "views/accountant_service_views.xml",
        "views/accountant_report_views.xml",
    ],
}
